import type { ContentItem } from "./types";

export const demoItems: ContentItem[] = [
  {
    id: "cnt_01",
    topic: "How B2B brands can turn search intent into a content engine",
    project: "AXIS Consulting",
    group: "July 2026",
    funnel: "TOFU",
    briefStatus: "BRIEF_READY",
    writer: "Nadia Rahman",
    publisher: "Robert Chen",
    plannedDate: "Jul 25, 2026",
    automationStatus: "NEEDS_REVIEW",
    priority: "HIGH",
    progress: 72,
    liveUrl: "https://axis.example.com/search-intent",
    channels: 5,
    media: true,
    updatedAt: "12 min ago",
    briefText: "Explain a practical framework for connecting search intent, editorial planning, and measurable business outcomes for B2B teams.",
    copies: {
      "Facebook + Instagram": "Search intent is more than a keyword list. It is a signal about what your audience needs next. Here is a practical way to turn that signal into a content engine.",
      LinkedIn: "The best B2B content programs start with a simple question: what is the audience trying to solve right now? Our latest framework connects search intent to a repeatable editorial system.",
      YouTube: "Turn Search Intent Into a B2B Content Engine",
      GBP: "Learn how B2B teams can use search intent to plan content that supports real business goals.",
      Reddit: "What frameworks are you using to move from keyword research to a useful B2B editorial roadmap? We tested a simple intent-first approach.",
    },
  },
  {
    id: "cnt_02",
    topic: "Technical SEO migration checklist for growing websites",
    project: "Growth Lab",
    group: "July 2026",
    funnel: "MOFU",
    briefStatus: "IN_PROGRESS",
    writer: "Samira Islam",
    publisher: "—",
    plannedDate: "Jul 28, 2026",
    automationStatus: "NOT_STARTED",
    priority: "NORMAL",
    progress: 38,
    channels: 0,
    media: false,
    updatedAt: "1 hr ago",
    briefText: "Create a migration checklist that helps marketing and engineering teams avoid traffic loss during a site move.",
    copies: {},
  },
  {
    id: "cnt_03",
    topic: "The quiet cost of publishing without an approval workflow",
    project: "AXIS Consulting",
    group: "August 2026",
    funnel: "BOFU",
    briefStatus: "BRIEF_READY",
    writer: "Nadia Rahman",
    publisher: "Maya Patel",
    plannedDate: "Aug 02, 2026",
    automationStatus: "APPROVED",
    priority: "URGENT",
    progress: 94,
    liveUrl: "https://axis.example.com/approval-workflows",
    channels: 5,
    media: true,
    updatedAt: "3 hr ago",
    briefText: "Show why approval is a safety mechanism, not a bottleneck, and outline a lightweight approval model for content teams.",
    copies: {
      "Facebook + Instagram": "A fast publishing workflow is only useful when it is safe. A clear approval gate protects the brand, the team, and the audience.",
      LinkedIn: "Approval does not have to slow down content operations. The right workflow makes ownership visible and reduces avoidable publishing mistakes.",
      YouTube: "Why Content Approval Is a Safety System",
      GBP: "Build a safer content workflow with a clear, accountable approval step.",
      Reddit: "How do you structure approvals without turning every post into a long committee process?",
    },
  },
  {
    id: "cnt_04",
    topic: "Content refresh playbook: from audit to measurable lift",
    project: "Growth Lab",
    group: "August 2026",
    funnel: "MOFU",
    briefStatus: "BRIEF_READY",
    writer: "Fahim Chowdhury",
    publisher: "Maya Patel",
    plannedDate: "Aug 05, 2026",
    automationStatus: "READY_TO_PUBLISH",
    priority: "HIGH",
    progress: 88,
    liveUrl: "https://growthlab.example.com/content-refresh",
    channels: 5,
    media: true,
    updatedAt: "Yesterday",
    briefText: "Turn content audits into a prioritized refresh plan with clear success criteria and ownership.",
    copies: {
      "Facebook + Instagram": "A content refresh is not a rewrite for the sake of a rewrite. It is a focused investment in pages with a clear opportunity to improve.",
      LinkedIn: "The most useful content audit ends with a decision: refresh, consolidate, redirect, or retire. Here is the playbook we use to turn analysis into action.",
      YouTube: "The Content Refresh Playbook",
      GBP: "Discover a practical playbook for refreshing content and measuring the lift.",
      Reddit: "What makes a content refresh worth the effort in your team? We are comparing traffic, intent, and conversion signals.",
    },
  },
  {
    id: "cnt_05",
    topic: "What changes when AI becomes part of the editorial workflow",
    project: "AXIS Consulting",
    group: "August 2026",
    funnel: "TOFU",
    briefStatus: "NOT_STARTED",
    writer: "—",
    publisher: "—",
    plannedDate: "Aug 11, 2026",
    automationStatus: "FAILED",
    priority: "NORMAL",
    progress: 14,
    channels: 0,
    media: false,
    updatedAt: "Yesterday",
    briefText: "Explore the operational changes teams need when AI-assisted copy becomes part of the normal content process.",
    copies: {},
  },
];

export const activity = [
  { name: "Nadia Rahman", action: "submitted copy for review", target: "Search intent content engine", time: "12 min ago", tone: "blue" },
  { name: "Maya Patel", action: "approved social copy", target: "Publishing without approval", time: "3 hr ago", tone: "green" },
  { name: "System", action: "publishing job failed", target: "AI editorial workflow", time: "Yesterday", tone: "red" },
  { name: "Samira Islam", action: "updated brief status", target: "Technical SEO migration checklist", time: "Yesterday", tone: "purple" },
];
